include $(THEOS)/makefiles/common.mk

TWEAK_NAME = KbdVol

KbdVol_FILES = KbdVol.m KbdAudio.m
KbdVol_CFLAGS = -fobjc-arc -Wall -I../shared
KbdVol_FRAMEWORKS = UIKit Foundation AVFoundation AudioToolbox

include $(THEOS_MAKE_PATH)/tweak.mk